tags:
  [
    {
      frame: "tag_2",
      id: 2,
      corners: [
        [-0.003, 0.003, 0.0],
        [0.003, 0.003, 0.0],
        [0.003, -0.003, 0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
