# STag parameters
libraryHD: 11
errorCorrection: 5

# Camera configuration
camera_info_topic: /raspicam/camera_info
raw_image_topic: /raspicam/image
is_compressed: false

# Node configuration
tag_tf_prefix: STag_
show_markers: true
publish_tf: true
